TARGETS = copy

copy :
	cp Figure2.png ~/GoogleDrive/Manuscripts/neuravi/Figures/Figure2.png
	cp Figure3_dataset_size.pdf ~/GoogleDrive/Manuscripts/neuravi/Figures/Figure3.png
	cp Figure4_entromaps.png ~/GoogleDrive/Manuscripts/neuravi/Figures/Figure4.png
	cp Figure5_fragility_maps.png ~/GoogleDrive/Manuscripts/neuravi/Figures/Figure5.png
	cp Figure6_Raman_m_Tg.png ~/GoogleDrive/Manuscripts/neuravi/Figures/Figure6.png
	cp SupplementaryFigure1_TernaryData.png ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure1.png
	cp SupplementaryFigure2.pdf ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure2.pdf
	cp SupplementaryFigure3.png ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure3.png
	cp SupplementaryFigure4.png ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure4.png
	cp SupplementaryFigure5.png ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure5.png
	cp SupplementaryFigure6_Raman_preds.pdf ~/GoogleDrive/Manuscripts/neuravi/Figures/SupplementaryFigure6.pdf
